[minify]
disableXML = false
minifyOutput = true
disableCSS = false
disableJS = false

[minify.tdewolff]
  [minify.tdewolff.html]
    keepComments = false
    keepWhitespace = false
  [minify.tdewolff.json]
    keepWhitespace = false

  [minify.tdewolff.svg]
    precision = 1  

[[build.cachebusters]]
  source = "assets/js/.*"
  target = "js"

[[build.cachebusters]]
  source = "assets/css/.*"
  target = "css"

[imaging]
  quality = 75
  resampleFilter = "Lanczos"



[services]
  [services.googleAnalytics]
    id = "G-6CE6YFM36C"  